App/models.py
  
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from App import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def get_reset_token(self, expires_sec=1800):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

class Comment(db.Model):
    id = id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text, nullable=False)
    
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'), nullable=False)

App/posts/forms.py
from tokenize import Comment
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Write blog here ...', validators=[DataRequired()])
    picture = FileField('Upload image here', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post Blog')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment...', validators=[DataRequired()])
    submit = SubmitField('comment')

App/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from App.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from App.auth.views import users
    from App.posts.views import posts
    from App.main.views import main
    app.register_blueprint(users)
    app.register_blueprint(posts)
    app.register_blueprint(main)


    with app.app_context():
        db.create_all()


    

    return app

App/main/views.py
from flask import render_template, request, Blueprint
from App.models import Post
import requests
import json

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    r = requests.get('http://quotes.stormconsultancy.co.uk/random.json')
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts,qoutes=json.loads(r.text)['quote'],author=json.loads(r.text)['author'])


@main.route("/about")
def about():
    return render_template('about.html', title='About')

App/posts/views.py
from crypt import methods
import imp
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from App import db
from App.models import Post,Comment
from App.posts.forms import PostForm,CommentForm
from App.posts.utils import save_picture
posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])

def new_post():
    form = PostForm()
    posts = Post.query.order_by(Post.date_posted.desc())
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            image_file = picture_file
        post = Post(title=form.title.data,content=form.content.data,image_file=image_file,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Blog has been created!', 'success')
        return redirect(url_for('posts.new_post'))
    
    return render_template('create_post.html', title='New Post',
                           form=form,posts=posts)

@posts.route("/post/<int:post_id>",methods=['GET','POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)

    comment = Comment.query.order_by(Comment.id.desc())
    # add coment 
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment=form.comment.data,post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment was added')
        return redirect(url_for('posts.new_post'))
    return render_template('post.html', title=post.title, post=post,form=form,comment=comment)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route("/comment/new")
@login_required
def add_comment():
    pass


         

App/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

App/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
       <div class="container">
           <div class="row">
               <div class="col-md-8">
                   <div class="card">
                       <div class="card-body">
                        <form method="POST" action="" enctype="multipart/form-data">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Account Info</legend>
                                <div class="form-group">
                                    {{ form.username.label(class="form-control-label") }}
                
                                    {% if form.username.errors %}
                                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.username.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.username(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.picture.label() }} <br>
                                    {{ form.picture(class="form-control-file") }}
                                    {% if form.picture.errors %}
                                        {% for error in form.picture.errors %}
                                            <span class="text-danger">{{ error }}</span></br>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-outline-info mt-2") }}
                            </div>
                        </form>
                       </div>
                   </div>
               </div>
           </div>
       </div>
    </div>
{% endblock content %}

App/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="">

    <div class="container">

      
        <div class="row">
       
        <div class="col-md-2"></div>
        
        <div class="col-md-8">
        <h4 class="text-info ">Create your Blog</h4> <br>
           <div class="card">
               <div class="card-body">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {{ form.title.label(class="form-control-label") }}
                            {% if form.title.errors %}
                                {{ form.title(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.title(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                  
                        <div class="form-group">
                            {{ form.content.label(class="form-control-label") }}
                            {% if form.content.errors %}
                                {{ form.content(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.content(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                       
                            <div class="form-group mt-2">
                                {{ form.picture.label() }} <br>
                                {{ form.picture(class="form-control-file") }}
                                {% if form.picture.errors %}
                                    {% for error in form.picture.errors %}
                                        <span class="text-danger">{{ error }}</span></br>
                                    {% endfor %}
                                {% endif %}
                            </div>
                       
                    </fieldset>
                    
              
               </div>
           </div>


           <div class="form-group mt-4">
            {{ form.submit(class="btn btn-white") }}
        </div>
        </div>

        

    </form>
        <div class="col-md-2"></div>
        </div>

       
    </div>

</div>
{% endblock content %}

App/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <div class="container">
      <div class="row">

        <div class="col-md-7">

          <p class="display-5">&ldquo; {{qoutes}}  &rdquo;</p>

          <p class="text-muted">- <i>{{author}}</i> </p>

        </div>
        <div class="col-md-5">
          <img src="{{url_for('static',filename='assets/motive.png')}}" alt="" height="300">
        </div>
        <!-- <div class="col-md-12">
         
            {{qoutes}}
            <br>
            {{author}}
          </div> -->
        </div>
      </div>
    </div>

    <div class="row mt-4">
    {% for post in posts.items %}
    
        
        <!-- <div class="col-md-6">
          <div class="card blog">
            <div class="card-body">
              <article class="media  mt-4">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                  </div>
                  <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                  <p class="article-content">{{ post.content }}</p>
                </div>
              </article>
            </div>
          </div>
        </div>
         -->

         <div class="col-md-6">
          <div class="card">
            <img src="{{ url_for('static', filename='uploads/' + post.image_file) }}" class="card-img-top" alt="Fissure in Sandstone" height="300"/>
            <div class="card-body">
             
              <h5 class="card-title"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h5>

              <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
              <p>Posted By <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></p>

              <p>On <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small></p>
              <p class="card-text">{{ post.content }}</p>
             
            </div>
          </div>
         </div>
     

        
    {% endfor %}

    </div>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4 mt-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

App/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css"
rel="stylesheet"
/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <!-- Navbar -->
    <header class="site-header">
<nav class="navbar navbar-expand-lg navbar-light bg-#f4f1de fixed-top">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        Blog Site
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
      
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
    

      {% if current_user.is_authenticated %}

      <a class="text-reset me-3" href="{{ url_for('posts.new_post') }}">
        Post Blog
       </a>
      <!-- Avatar -->
      <div class="dropdown">
        <a
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuAvatar"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}"
            class="rounded-circle"
            height="25"
            alt="Black and White Portrait of a Man"
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuAvatar"
        >
          <li>
            <a class="dropdown-item" href="{{ url_for('users.account') }}">My profile</a>
          </li>
         
          <li>
            <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
    {% else %}

    <a class="text-reset me-3" href="{{ url_for('users.login') }}">
     Login
    </a>

    <a class="text-reset me-3" href="{{ url_for('users.register') }}">
      Register
     </a>

    {% endif %}


    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
    </header>
<!-- Navbar -->
    <main role="main" class="container mt-4">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
         
        </div>
       
      </div>
      {% block content %}{% endblock %}

    </main>


    <!-- footer -->

    <footer class="bg-#003049 text-center text-lg-start mb-4">
      <!-- Grid container -->
      <div class="container p-4">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">Footer text</h5>
    
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
              molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
              aliquam voluptatem veniam, est atque cumque eum delectus sint!
            </p>
          </div>
          <!--Grid column-->
    
          <!--Grid column-->
          <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">Footer text</h5>
    
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
              molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
              aliquam voluptatem veniam, est atque cumque eum delectus sint!
            </p>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center p-3" >
        © 2022 Copyright:
        <a class="text-dark" href="#">Blogsite.com</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <!-- MDB -->

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"
    ></script>
</body>
</html>

App/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="">
        <div class="container">
         <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Welcome Back 👋</legend>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password.label(class="form-control-label") }}
                                    {% if form.password.errors %}
                                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.password.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-check mt-2">
                                    {{ form.remember(class="form-check-input") }}
                                    {{ form.remember.label(class="form-check-label") }}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-success") }} <br>

                                <small class="text-muted mt-2">
                                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                                </small>
                            </div>
                        </form>

                        <div class="border-top pt-3">
                            <small class="text-muted ml-2">
                                Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
                            </small>
                        </div>
                    </div>

                    

                    <p class="mt-4"></p>
                
                </div>
            </div>
            <div class="col-md-5">
                <img src="{{url_for('static',filename='assets/login.png')}}" alt="" height="300">
            </div>
         </div>
        </div>
    </div>
  
{% endblock content %}

App/templates/post.html
{% extends "layout.html" %}
{% block content %}

<p><i class="fas fa-angle-left"></i><a href="{{url_for('main.home')}}"> Back</a></p>
  <article class="media content-section">
    
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
 

    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <div class="card-body">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>

      <hr>

      <div class="card">
        <div class="card-body bg-#cdb4db">
  
          {% for c in comment %}
  
          <div class="card mt-2">
            <div class="card-body">
              <p><i> {{c.comment}}</i></p>
            </div>
           
          </div>
          
          {% endfor %}
  
        </div>
      </div>


      <form action="" method="POST">
        {{ form.hidden_tag() }}
  
        <div class="form-group">
          {{ form.comment.label(class="form-control-label") }}
          {% if form.comment.errors %}
              {{ form.comment(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.comment.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.comment(class="form-control form-control-lg") }}
          {% endif %}
      </div>
  
      <div class="form-group mt-4">
        {{ form.submit(class="btn btn-white") }}
    </div>
  
      </form>
        </div>
      
      </div>
      
      </div>
    </div>
 
   

    <!-- comment card  -->
   

    <!-- end comment card -->
    <!-- add comment -->


    <!-- end comment -->
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

App/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}